### ISSUE TITLE
alert  xvda1 does not exists

### ISSUE THREAD

**Issue by txsastre** [guestisp/xen-to-pve#1]
hi there.

once importe the VM to proxmox, when I start it, it gives me this error "alert  xvda1 does not exists"

the original VM had the disks mounted by UUID, so I don't understand why is searching for xvda1.

any clues ? 

by the way, thanks for your script.

**Comment by guestisp** [comment]
I've never faced this error before, I can't help you.
I've migrated tons of VM with my script with no issue at all.

**Comment by txsastre** [comment]
also tried with others machines... those don't start, I can see them starting but screen stays in black (debian)

do I have to remove firts xen-tools ? how do I have to attach the imported disk to the VM ? Virtio, IDE, SCSI ? 

Has to be created the VM with special characteristics ? 

meanwhile I'm still testing combinations.

thanks.

**Comment by guestisp** [comment]
We only use VirtIO. Ensure that the following modules are added to initramfs:

```
virtio_blk
virtio_pci
```

**Comment by txsastre** [comment]
Hi. Thanks.
do i have to add them before migrating? When the vm is still on xen? Guess so. 

Also tried with Windows. The ones that didn't have installed xentools imported fine. The ones that have it, no.
same happened when testing oVirt

**Comment by guestisp** [comment]
We don't use Windows.
Yes, you have to install those modules when VM is still on Xen and the update the initramfs.

**Comment by txsastre** [comment]
you're very lucky if you don't need windows.

well I tried again. the initial load has a bug.
when debian starts, in the blue screen press 'E', then you will see where the grub is trying load, in my case was /dev/xvda1, changed to /dev/sda1. Worked.
Once started : update-grub. and that's all.

thank you !
