### ISSUE TITLE
pv vm stuck on booting

### ISSUE THREAD

**Issue by empereira** [guestisp/xen-to-pve#4]
hi,

Are the VMs you migrated PV mode?

I migrated one with your script and everything is fine, but it gets 
stuck on the message, `Booting from hard disk`.

Can you tell me if I need to modify something in the VM before migrating?

**Comment by guestisp** [comment]
did you install GRUB or a bootloader? PV doesn't need a bootloader is it's booted directly from pygrub.

you have to install a bootloader on each disk

**Comment by empereira** [comment]
Hi,

I installed grub but it ends up stuck in the same message.

how do i install the bootloader?

**Comment by guestisp** [comment]
read some tutorial, this is not related to this script but on how to manage a Linux server

**Comment by empereira** [comment]
Ok. Thanks!
